global:
  scrape_interval: 15s
scrape_configs:
  - job_name: getscience-backend-metrics
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - getscience:8080
rule_files:
  - "/etc/prometheus/rules/application.yml"